"use client"

import { useState, useEffect } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Skeleton } from "@/components/ui/skeleton"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { FileText, Database, Code, Link as LinkIcon, AlertCircle, CheckCircle2 } from "lucide-react"
import { AlertTriangle } from "lucide-react"

interface PromptDetails {
  id: string
  promptTemplate?: string | null
  renderedPrompt?: string | null
  responseText?: string | null
  provider?: string | null
  modelUsed?: string | null
  tokensUsed?: number | null
  createdAt: string
  user?: {
    id: string
    name?: string | null
    email?: string | null
  } | null
}

interface DataSource {
  type: string
  id: string
  snippet: string
}

interface AuditabilityModalProps {
  open: boolean
  onClose: () => void
  promptId?: string | null
  dataSources?: DataSource[]
  recommendation?: {
    type: string
    action: string
    explain: string
    confidence: number
  }
}

export function AuditabilityModal({
  open,
  onClose,
  promptId,
  dataSources = [],
  recommendation,
}: AuditabilityModalProps) {
  const [promptDetails, setPromptDetails] = useState<PromptDetails | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (open && promptId) {
      fetchPromptDetails()
    } else {
      setPromptDetails(null)
      setError(null)
    }
  }, [open, promptId])

  const fetchPromptDetails = async () => {
    if (!promptId) return

    setLoading(true)
    setError(null)

    try {
      const response = await fetch(`/api/v1/prompts/${promptId}`)
      if (!response.ok) {
        throw new Error("Failed to fetch prompt details")
      }

      const data = await response.json()
      if (data.ok && data.prompt) {
        setPromptDetails(data.prompt)
      } else {
        throw new Error("Invalid response format")
      }
    } catch (err: any) {
      setError(err.message || "Failed to load prompt details")
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            AI-CFO Auditability — No Black Box
          </DialogTitle>
          <DialogDescription>
            Every recommendation is linked to exact data sources and prompts for full transparency
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="recommendation" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="recommendation">Recommendation</TabsTrigger>
            <TabsTrigger value="prompt">Prompt & Model</TabsTrigger>
            <TabsTrigger value="data">Data Sources</TabsTrigger>
          </TabsList>

          <TabsContent value="recommendation" className="space-y-4">
            {recommendation ? (
              <Card>
                <CardHeader>
                  <CardTitle>AI Recommendation</CardTitle>
                  <CardDescription>Generated by AI-CFO with full traceability</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <Badge variant="outline">{recommendation.type}</Badge>
                      <Badge variant="secondary">
                        {Math.round(recommendation.confidence * 100)}% confidence
                      </Badge>
                    </div>
                    <h4 className="font-semibold mb-2">{recommendation.action}</h4>
                    <p className="text-sm text-muted-foreground">{recommendation.explain}</p>
                  </div>

                  {promptId && (
                    <Alert>
                      <LinkIcon className="h-4 w-4" />
                      <AlertDescription>
                        <strong>Prompt ID:</strong> {promptId}
                        <br />
                        <span className="text-xs text-muted-foreground">
                          View the exact prompt used to generate this recommendation
                        </span>
                      </AlertDescription>
                    </Alert>
                  )}
                </CardContent>
              </Card>
            ) : (
              <Alert>
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>No recommendation details available</AlertDescription>
              </Alert>
            )}
          </TabsContent>

          <TabsContent value="prompt" className="space-y-4">
            {loading ? (
              <div className="space-y-2">
                <Skeleton className="h-32 w-full" />
                <Skeleton className="h-32 w-full" />
              </div>
            ) : error ? (
              <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            ) : promptDetails ? (
              <div className="space-y-4">
                <Card>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <CardTitle>Prompt Details</CardTitle>
                      <div className="flex gap-2">
                        {promptDetails.provider && (
                          <Badge variant="outline">{promptDetails.provider}</Badge>
                        )}
                        {promptDetails.modelUsed && (
                          <Badge variant="secondary">{promptDetails.modelUsed}</Badge>
                        )}
                      </div>
                    </div>
                    <CardDescription>
                      Created: {new Date(promptDetails.createdAt).toLocaleString()}
                      {promptDetails.user && (
                        <> • By: {promptDetails.user.name || promptDetails.user.email}</>
                      )}
                      {promptDetails.tokensUsed && <> • Tokens: {promptDetails.tokensUsed}</>}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {promptDetails.promptTemplate && (
                      <div>
                        <h4 className="font-semibold mb-2 flex items-center gap-2">
                          <Code className="h-4 w-4" />
                          System Prompt
                        </h4>
                        <ScrollArea className="h-32 w-full rounded-md border p-4">
                          <pre className="text-xs whitespace-pre-wrap">
                            {promptDetails.promptTemplate}
                          </pre>
                        </ScrollArea>
                      </div>
                    )}

                    {promptDetails.renderedPrompt && (
                      <div>
                        <h4 className="font-semibold mb-2 flex items-center gap-2">
                          <FileText className="h-4 w-4" />
                          Rendered Prompt (User Query + Context)
                        </h4>
                        <ScrollArea className="h-48 w-full rounded-md border p-4">
                          <pre className="text-xs whitespace-pre-wrap">
                            {promptDetails.renderedPrompt}
                          </pre>
                        </ScrollArea>
                      </div>
                    )}

                    {promptDetails.responseText && (
                      <div>
                        <h4 className="font-semibold mb-2 flex items-center gap-2">
                          <CheckCircle2 className="h-4 w-4" />
                          LLM Response
                        </h4>
                        <ScrollArea className="h-48 w-full rounded-md border p-4">
                          <pre className="text-xs whitespace-pre-wrap">
                            {promptDetails.responseText}
                          </pre>
                        </ScrollArea>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </div>
            ) : (
              <Alert>
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  {promptId
                    ? "Prompt details not available. The prompt may not have been saved."
                    : "No prompt ID linked to this recommendation"}
                </AlertDescription>
              </Alert>
            )}
          </TabsContent>

          <TabsContent value="data" className="space-y-4">
            {dataSources.length > 0 ? (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Database className="h-5 w-5" />
                    Data Sources
                  </CardTitle>
                  <CardDescription>
                    Exact data sources used to generate this recommendation
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {dataSources.map((source, index) => (
                      <Card key={index} className="border-l-4 border-l-primary">
                        <CardContent className="p-4">
                          <div className="flex items-start justify-between mb-2">
                            <Badge variant="outline">{source.type}</Badge>
                            <span className="text-xs text-muted-foreground">ID: {source.id}</span>
                          </div>
                          <ScrollArea className="h-24 w-full rounded-md border p-2 mt-2">
                            <p className="text-xs whitespace-pre-wrap">{source.snippet}</p>
                          </ScrollArea>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ) : (
              <Alert>
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>No data sources available for this recommendation</AlertDescription>
              </Alert>
            )}
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  )
}
























