/**
 * Ambient Intelligence Agent
 * 
 * Inspired by Runway's "Ambient Intelligence" and Pigment's "Smart Insights".
 * Proactively scans financial data in the background to surface anomalies,
 * variance alerts, and strategic opportunities without user prompting.
 */

import prisma from '../../config/database';
import { v4 as uuidv4 } from 'uuid';
import { overviewDashboardService } from '../overview-dashboard.service';

export const ambientIntelligenceService = {
  /**
   * Run a background scan across all active organizations
   * Intended to be run via a cron job (e.g., daily)
   */
  async runGlobalScan() {
    console.log('[Ambient] Starting global proactive scan for anomalies...');
    
    // Get organizations that have had recent activity (transactions or model runs)
    const activeOrgs = await prisma.userOrgRole.findMany({
      select: { orgId: true },
      distinct: ['orgId'],
      take: 100 // Batching
    });

    let insightsGenerated = 0;
    for (const org of activeOrgs) {
      try {
        const insight = await this.scanOrganization(org.orgId);
        if (insight) insightsGenerated++;
      } catch (err) {
        console.error(`[Ambient] Failed to scan org ${org.orgId}:`, err);
      }
    }

    console.log(`[Ambient] Global scan complete. Generated ${insightsGenerated} proactive insights.`);
    return insightsGenerated;
  },

  /**
   * Scan a specific organization for financial anomalies
   */
  async scanOrganization(orgId: string) {
    try {
      const dashboard = await overviewDashboardService.getOverviewData(orgId);
      if (!dashboard || !dashboard.monthlyRevenue) return null;

      const insights: any[] = [];

      // 1. Burn Rate Spike Anomaly
      const burnVariance = dashboard.burnRateChange > 15 ? dashboard.burnRateChange : 0;
      if (burnVariance > 0) {
        insights.push({
          type: 'risk',
          category: 'burn_rate',
          title: 'Unusual Burn Rate Spike Detected',
          description: `Monthly expenses have surged by ${burnVariance.toFixed(1)}% compared to the previous period.`,
          recommendation: `Review the largest contributing expense categories (e.g., ${dashboard.expenseBreakdown?.[0]?.name || 'OpEx'}) to ensure capital efficiency.`,
          impact: { metric: 'runway', severity: 'high' }
        });
      }

      // 2. Runway Danger Zone
      if (dashboard.cashRunway > 0 && dashboard.cashRunway < 6) {
        insights.push({
          type: 'warning',
          category: 'liquidity',
          title: 'Critical Cash Runway',
          description: `Cash runway has dropped to ${dashboard.cashRunway.toFixed(1)} months at the current net burn.`,
          recommendation: 'Immediate action required. Consider pausing non-essential hiring and restructuring SaaS contracts.',
          impact: { metric: 'survival', severity: 'critical' }
        });
      }

      // 3. Revenue Opportunity (Rule of 40)
      const ruleOf40 = dashboard.revenueGrowth + ((dashboard.monthlyRevenue - dashboard.monthlyBurnRate) / dashboard.monthlyRevenue * 100);
      if (ruleOf40 > 40 && dashboard.revenueGrowth > 20) {
        insights.push({
          type: 'opportunity',
          category: 'growth',
          title: 'Hyper-Growth Efficiency Achieved',
          description: `Your Rule of 40 score is ${ruleOf40.toFixed(0)}, indicating excellent capital-efficient growth.`,
          recommendation: 'With a strong LTV:CAC proxy, this is an optimal time to increase marketing spend to capture market share.',
          impact: { metric: 'valuation', severity: 'positive' }
        });
      }

      if (insights.length === 0) return null;

      // Group the insights into a cohesive "Ambient Analysis"
      // Check if we've already generated a similar insight this week to prevent spam
      const oneWeekAgo = new Date();
      oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

      const recentInsight = await prisma.aICFOPlan.findFirst({
        where: {
          orgId,
          name: { contains: 'Ambient Insight:' },
          createdAt: { gte: oneWeekAgo }
        }
      });

      if (recentInsight) return null; // Skip if already alerted recently

      const topInsight = insights.sort((a, b) => a.severity === 'critical' ? -1 : 1)[0];

      // Auto-generate an AI CFO "Plan" that acts as a proactive alert
      const adminUsers = await prisma.userOrgRole.findFirst({
        where: { orgId, role: { in: ['admin', 'owner', 'finance'] } }
      });

      if (!adminUsers) return null;

      const plan = await prisma.aICFOPlan.create({
        data: {
          orgId,
          name: `Ambient Insight: ${topInsight.title}`,
          description: 'Proactively generated by FinaPilot Ambient Intelligence',
          status: 'completed',
          createdById: adminUsers.userId,
          planJson: {
            goal: 'Proactive System Monitoring',
            generatedAt: new Date().toISOString(),
            structuredResponse: {
              intent: 'ambient_insight',
              natural_text: `I continuously monitor your financial health, and I've identified an important trend. ${topInsight.description} ${topInsight.recommendation}`,
              calculations: {
                runway: dashboard.cashRunway,
                burnRate: dashboard.monthlyBurnRate,
                revenue: dashboard.monthlyRevenue
              }
            },
            ambientInsights: insights,
            metadata: {
              modelUsed: 'deterministic_ambient',
              worker: 'nodejs',
              isProactive: true
            }
          }
        }
      });

      return plan;
    } catch (e) {
      console.error(`[Ambient] Error scanning org ${orgId}:`, e);
      return null;
    }
  }
};
