"""
FinaPilot Unified Transaction Schema

This schema normalizes transactions from diverse sources (Stripe, QuickBooks, SAP, etc.)
into a single canonical format for consistent processing, deduplication, and audit tracking.
"""

from dataclasses import dataclass, asdict
from typing import Optional, Dict, Any, List
from datetime import datetime
from decimal import Decimal
from enum import Enum
import hashlib
import json


class TransactionStatus(str, Enum):
    """Standard transaction statuses across all platforms."""
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    REFUNDED = "refunded"
    HELD = "held"


class TransactionCategory(str, Enum):
    """Standard transaction categories for scenario planning & reporting."""
    REVENUE = "revenue"
    EXPENSE = "expense"
    TRANSFER = "transfer"
    PAYROLL = "payroll"
    PAYMENT_PROCESSING = "payment_processing"
    TAX = "tax"
    LOAN = "loan"
    INVESTMENT = "investment"
    DIVIDEND = "dividend"
    OTHER = "other"


@dataclass
class UnifiedTransaction:
    """
    Canonical transaction representation across all financial platforms.
    
    Core Fields:
    - internal_id: Unique identifier generated by FinaPilot for deduplication
    - trace_id: API request trace ID for audit/provenance tracking
    - source_id: Platform-specific identifier (e.g., "stripe_pi_1234abcd")
    - platform: Source platform (quickbooks, stripe, xero, etc.)
    - transaction_date: Date the transaction occurred
    - net_amount: Amount after platform fees (actual revenue/expense value)
    - tax_amount: Sales tax, VAT, GST, or income tax
    - gross_amount: Amount before fees (gross revenue)
    - currency: ISO 4217 currency code
    - status: Transaction status
    - category: Categorization for scenario planning
    - description: Human-readable transaction description
    - counterparty_id: Customer/vendor ID from source system
    - counterparty_name: Customer/vendor name
    - metadata: Platform-specific metadata for context
    - audit_hash: SHA256(date + amount + currency + platform_id) for deduplication
    - created_at: When record was created in FinaPilot
    - sync_timestamp: When this record was pulled from platform
    """
    
    # Required core fields
    transaction_date: datetime
    net_amount: Decimal
    currency: str
    platform: str
    source_id: str
    
    # Optional but important fields
    internal_id: Optional[str] = None
    trace_id: Optional[str] = None
    status: TransactionStatus = TransactionStatus.COMPLETED
    category: TransactionCategory = TransactionCategory.OTHER
    
    # Financial breakdown
    gross_amount: Optional[Decimal] = None
    tax_amount: Optional[Decimal] = None
    fees_amount: Optional[Decimal] = None  # Platform fees (Stripe, Razorpay, etc.)
    
    # Description & context
    description: Optional[str] = None
    counterparty_id: Optional[str] = None
    counterparty_name: Optional[str] = None
    
    # Deduplication & tracking
    audit_hash: Optional[str] = None
    created_at: Optional[datetime] = None
    sync_timestamp: Optional[datetime] = None
    
    # Platform-specific metadata (flexible schema for future platforms)
    metadata: Optional[Dict[str, Any]] = None
    raw_payload: Optional[Dict[str, Any]] = None  # Full API response for debugging
    
    def __post_init__(self):
        """Validate and normalize transaction data."""
        # Ensure currency is uppercase
        if isinstance(self.currency, str):
            self.currency = self.currency.upper()
        
        # Generate audit hash for deduplication if not already present
        if not self.audit_hash:
            self.audit_hash = self._generate_audit_hash()
        
        # Set creation timestamp if not provided
        if not self.created_at:
            self.created_at = datetime.utcnow()
        
        # If transaction_date is string, parse it
        if isinstance(self.transaction_date, str):
            self.transaction_date = datetime.fromisoformat(
                self.transaction_date.replace('Z', '+00:00')
            )
    
    def _generate_audit_hash(self) -> str:
        """
        Generate SHA256 hash for deduplication.
        
        Hash is based on (date + amount + currency + platform_id) to ensure
        uniqueness while being platform-agnostic.
        
        This prevents double-counting when users manually export + auto-sync
        or when connectors retry failed requests.
        """
        hash_input = f"{self.transaction_date.date()}|{self.net_amount}|{self.currency}|{self.platform}|{self.source_id}"
        return hashlib.sha256(hash_input.encode()).hexdigest()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        data = asdict(self)
        
        # Convert enums to strings
        if isinstance(self.status, TransactionStatus):
            data['status'] = self.status.value
        if isinstance(self.category, TransactionCategory):
            data['category'] = self.category.value
        
        # Convert Decimals to strings for JSON serialization
        for key in ['net_amount', 'gross_amount', 'tax_amount', 'fees_amount']:
            if data[key] is not None and isinstance(data[key], Decimal):
                data[key] = str(data[key])
        
        # Convert datetimes to ISO strings
        for key in ['transaction_date', 'created_at', 'sync_timestamp']:
            if data[key] is not None and isinstance(data[key], datetime):
                data[key] = data[key].isoformat()
        
        return data
    
    def to_json(self) -> str:
        """Serialize to JSON string."""
        return json.dumps(self.to_dict(), default=str)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'UnifiedTransaction':
        """Deserialize from dictionary."""
        # Convert string enums back to enum types
        if isinstance(data.get('status'), str):
            data['status'] = TransactionStatus(data['status'])
        if isinstance(data.get('category'), str):
            data['category'] = TransactionCategory(data['category'])
        
        # Convert string amounts back to Decimal
        for key in ['net_amount', 'gross_amount', 'tax_amount', 'fees_amount']:
            if data.get(key) is not None and isinstance(data[key], str):
                data[key] = Decimal(data[key])
        
        # Convert ISO strings back to datetime
        for key in ['transaction_date', 'created_at', 'sync_timestamp']:
            if data.get(key) is not None and isinstance(data[key], str):
                data[key] = datetime.fromisoformat(data[key].replace('Z', '+00:00'))
        
        return cls(**data)


@dataclass
class DeduplicationResult:
    """Result of deduplication check."""
    is_duplicate: bool
    existing_hash: Optional[str] = None
    conflict_type: Optional[str] = None  # 'exact_match', 'partial_match', 'similar'
    confidence: float = 1.0  # 0-1 confidence score
    message: Optional[str] = None


@dataclass
class SyncResult:
    """Result of a complete sync operation."""
    connector_type: str
    org_id: str
    trace_id: str
    
    total_records_fetched: int = 0
    total_records_processed: int = 0
    total_records_inserted: int = 0
    total_records_updated: int = 0
    total_records_skipped: int = 0
    total_duplicates_detected: int = 0
    
    errors: List[Dict[str, Any]] = None
    warnings: List[str] = None
    
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    status: str = "pending"  # pending, running, completed, failed
    
    def __post_init__(self):
        """Initialize lists if not provided."""
        if self.errors is None:
            self.errors = []
        if self.warnings is None:
            self.warnings = []
        if not self.started_at:
            self.started_at = datetime.utcnow()
    
    def add_error(self, error_type: str, message: str, details: Optional[Dict] = None):
        """Record an error during sync."""
        self.errors.append({
            'type': error_type,
            'message': message,
            'details': details,
            'timestamp': datetime.utcnow().isoformat(),
        })
    
    def add_warning(self, message: str):
        """Record a warning during sync."""
        self.warnings.append(message)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'connector_type': self.connector_type,
            'org_id': self.org_id,
            'trace_id': self.trace_id,
            'total_records_fetched': self.total_records_fetched,
            'total_records_processed': self.total_records_processed,
            'total_records_inserted': self.total_records_inserted,
            'total_records_updated': self.total_records_updated,
            'total_records_skipped': self.total_records_skipped,
            'total_duplicates_detected': self.total_duplicates_detected,
            'errors': self.errors,
            'warnings': self.warnings,
            'started_at': self.started_at.isoformat() if self.started_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'status': self.status,
        }
